config/routes.rb
# require_relative "../app/api/marker"

Marker::Application.routes.draw do
  mount API => '/'


  namespace :admin do
    resources :assessments
    resources :students
  end

  root :to => 'home#index'
end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
  attr_accessible :name, :total

  has_many :student_assessments
  has_many :students, :through => :student_assessments
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name

  has_many :student_assessments
  has_many :assessments, :through => :student_assessments
end

app/models/student_assessment.rb
class StudentAssessment < ActiveRecord::Base
  attr_accessible :mark, :reason

  belongs_to :assessment
  belongs_to :student
end

app/controllers/admin/assessments_controller.rb
class Admin::AssessmentsController < ApplicationController
  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = Assessment.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
    @assessment = Assessment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /assessments/new
  # GET /assessments/new.json
  def new
    @assessment = Assessment.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /assessments/1/edit
  def edit
    @assessment = Assessment.find(params[:id])
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = Assessment.new(params[:assessment])

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to [:admin, @assessment], notice: 'Assessment was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /assessments/1
  # PUT /assessments/1.json
  def update
    @assessment = Assessment.find(params[:id])

    respond_to do |format|
      if @assessment.update_attributes(params[:assessment])
        format.html { redirect_to [:admin, @assessment], notice: 'Assessment was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    @assessment = Assessment.find(params[:id])
    @assessment.destroy

    respond_to do |format|
      format.html { redirect_to admin_assessments_url }
    end
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(params[:student])
    if @student.save
      redirect_to [:admin, @student], :notice => "Successfully created student."
    else
      render :action => 'new'
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(params[:student])
      redirect_to [:admin, @student], :notice  => "Successfully updated student."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to admin_students_url, :notice => "Successfully destroyed student."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = Assessment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assessments }
    end
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
    @assessment = Assessment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assessment }
    end
  end

  # GET /assessments/new
  # GET /assessments/new.json
  def new
    @assessment = Assessment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assessment }
    end
  end

  # GET /assessments/1/edit
  def edit
    @assessment = Assessment.find(params[:id])
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = Assessment.new(params[:assessment])

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to @assessment, notice: 'Assessment was successfully created.' }
        format.json { render json: @assessment, status: :created, location: @assessment }
      else
        format.html { render action: "new" }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assessments/1
  # PUT /assessments/1.json
  def update
    @assessment = Assessment.find(params[:id])

    respond_to do |format|
      if @assessment.update_attributes(params[:assessment])
        format.html { redirect_to @assessment, notice: 'Assessment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    @assessment = Assessment.find(params[:id])
    @assessment.destroy

    respond_to do |format|
      format.html { redirect_to assessments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/admin/students_helper.rb
module Admin::StudentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/assessments/_form.html.erb
<%= form_for([:admin, @assessment]) do |f| %>
  <% if @assessment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assessment.errors.count, "error") %> prohibited this assessment from being saved:</h2>

      <ul>
      <% @assessment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.number_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/assessments/edit.html.erb
<h1>Editing assessment</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @assessment] %> |
<%= link_to 'Back', admin_assessments_path %>

app/views/admin/assessments/index.html.erb
<h1>Listing assessments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assessments.each do |assessment| %>
  <tr>
    <td><%= assessment.name %></td>
    <td><%= assessment.total %></td>
    <td><%= link_to 'Show', [:admin, assessment] %></td>
    <td><%= link_to 'Edit', edit_admin_assessment_path(assessment) %></td>
    <td><%= link_to 'Destroy', [:admin, assessment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Assessment', new_admin_assessment_path %>

app/views/admin/assessments/new.html.erb
<h1>New assessment</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_assessments_path %>

app/views/admin/assessments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @assessment.name %>
</p>

<p>
  <b>Total:</b>
  <%= @assessment.total %>
</p>


<%= link_to 'Edit', edit_admin_assessment_path(@assessment) %> |
<%= link_to 'Back', admin_assessments_path %>

app/views/admin/students/_form.html.erb
<%= form_for [:admin, @student] do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/students/edit.html.erb
<h1>Edit Student</h1>

<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin, @student] %> |
  <%= link_to "View All", admin_students_path %>
</p>

app/views/admin/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for student in @students %>
    <tr>
      <td><%= student.name %></td>
      <td><%= link_to "Show", [:admin, student] %></td>
      <td><%= link_to "Edit", edit_admin_student_path(student) %></td>
      <td><%= link_to "Destroy", [:admin, student], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Student", new_admin_student_path %></p>

app/views/admin/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_students_path %></p>

app/views/admin/students/show.html.erb
<h1>Student</h1>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <%= link_to "Edit", edit_admin_student_path(@student) %> |
  <%= link_to "Destroy", [:admin, @student], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_students_path %>
</p>

app/views/home/index.html.erb
<p>Nothing to see here.</p>

<p>Go to <a href="http://docs.marker.apiary.io/">Marker API docs</a> for details</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>